# Generated by Django 4.0.6 on 2022-07-09 08:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0002_rename_username_user_email_user_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registered_institutions',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
